
import { Metadata } from 'next'
import "./globals.css";
import Head from 'next/head';
import { Header } from "../../components/header";
import { Footer } from "../../components/footer";


const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <Head>
        <title>タイトル</title>
        <meta name="description" content="開発中" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <body>
        {children}
      </body>
    </html>
  )
}
