import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../../components/header";
import Footer from "../../components/footer";
import Form from "../../components/Button";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ハロー",
  description: "Generated by create next app",
};




export default function Layout({ children }) {
  return (
    <html>
      <body>
       
      <main>{children}</main>
      
      </body>
    </html>
  );
}
